### ISSUE TITLE
How to create a mock of SharedPreferences that are library specific?

### ISSUE THREAD

**Issue by mohan-dev1248** [IvanShafran/shared-preferences-mock#1]

**Comment by IvanShafran** [comment]
Hi!

Could you provide more info on this issue? It would be great to see a code sample.

If you use a third-party library and it doesn't allow to change internal prefs, then, unfortunately, shared-preference-mock library can't help you. 
This mock library targets on your code that can replace prefs implementation through DI, for example.

Sorry for the long response delay. I missed a notification about the issue.
